name: xtream_code_client
description: A Dart client for Xtream-compatible IPTV APIs with resilient parsing, diagnostics, and v2 compatibility helpers.
version: 2.0.0
homepage: https://github.com/pauli2406/xtream_code_client
repository: https://github.com/pauli2406/xtream_code_client.git
issue_tracker: https://github.com/pauli2406/xtream_code_client/issues

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  http: ^1.5.0
  json_annotation: ^4.9.0
  xml: ^6.6.1


dev_dependencies:
  build_runner:
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:
