name: xtream_code_client
description: "A WebClient to access a XTream Code API. 
It provides easy and efficient access to the API, with features 
like automatic retries and error handling."
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cronet_http: ^1.1.0
  cupertino_http: ^1.3.0
  fetch_client: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
