name: xtream_code_client
description: A WebClient to access a XTream Code API. It provides easy and efficient access to the API, with features like automatic retries and error handling.
version: 1.5.0
homepage: https://github.com/pauli2406/xtream_code_client
repository: https://github.com/pauli2406/xtream_code_client.git
issue_tracker: https://github.com/pauli2406/xtream_code_client/issues

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  cronet_http: ^1.3.4
  cupertino_http: ^2.2.0
  fetch_client: ^1.1.4
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0 
  path_provider: ^2.1.5 
  xml: ^6.5.0


dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5 
  mocktail: ^1.0.4 
  very_good_analysis: ">=8.0.0 <11.0.0"

platforms:
  android:
  ios:
  macos:
  web:
  windows:
